### ISSUE TITLE
Some objects are not valid

### ISSUE THREAD

**Issue by raphaelbastide** [libreobjet/libreobjet.github.io#19]
- [x] Missing license files for a couple of objects
- [x] Wrong format for list in objects yml files: refer to [Bouctje’s yml file](https://github.com/libreobjet/libreobjet.org/blob/master/content/1.objects/1.bouctje/project.yml). The correct format for list is `required_hardware: [hand saw, circular saw, sander, sand paper]`

**Comment by xuv** [comment]
Fixed.
